# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' build_beta_from_methylkit
#' 
#' build_beta_from_methylkit
#' @param test the result of methylkit with slopes including .data and  sample.ids
#' @return data.frame
#' 
#' @export
build_beta_from_methylkit <- function(test){
  mat <- matrix(as.vector(unlist(test@.Data)), 
                nrow = length(test@.Data[[1]]),
                ncol = length(test@.Data)) %>% 
    as.data.frame() %>% 
    dplyr::mutate(probe = paste0(V1,".",V2)) %>% 
    dplyr::select(-all_of(c("V1","V2","V3","V4")))
  detavector <- seq(from = 5, to = ncol(mat)+2, by = 3)
  message("decoding beta value")
  sample_df_list <- list()
  for (i in 1:length(detavector)){
    mat_temp <- mat %>% 
      dplyr::select(all_of(
        c("probe",
          paste0("V",detavector[i]),paste0("V",detavector[i]+1),paste0("V",detavector[i]+2)
          )
      )) %>% 
      dplyr::mutate(beta = as.numeric(.[[paste0("V",detavector[i]+1)]])/ as.numeric(.[[paste0("V",detavector[i])]])) %>% 
      dplyr::select(-all_of(c(paste0("V",detavector[i]),paste0("V",detavector[i]+1),paste0("V",detavector[i]+2)
      )
      )) %>% 
      dplyr::relocate(probe)
    colnames(mat_temp) <- c("probe",test@sample.ids[i])
    sample_df_list[[i]] <- mat_temp
  }
  message("encoding beta matrix")
  beta_df <- NULL
  for (i in 1:length(sample_df_list)){
    sampledf <- sample_df_list[[i]]
    message(glue::glue("processing sample {i}"))
    if (i == 1){
      beta_df <-  sampledf
    }else {
      beta_df <- beta_df %>% 
        dplyr::left_join(sampledf,by = "probe")
    }
  }
  return(beta_df)
}
