# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' flop_img_from_directory
#' 
#' flop_img_from_directory
#' @param working_dir the dir stores the images
#' @param img_format default as png
#' @return null
#' 
#' @export
flop_img_from_directory  <- function(working_dir,img_format = "png") {
  img_match <- glue::glue("*.{img_format}")
  png_images <- list.files(working_dir,
                           img_match,
                           full.names = FALSE)
  for (a in 1:length(png_images)){
    Imgdata <- EBImage::readImage(paste0(working_dir,png_images[a]), img_format) %>% 
      EBImage::flop() 
    EBImage::writeImage(Imgdata, paste0(working_dir,"flop_",png_images[a]), img_format,  quality = 100)
  }
  return(working_dir)
}
