# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' resize_img_from_directory
#' 
#' resize_img_from_directory
#' 
#' @param working_dir the dir stores the images
#' @param img_format default as png
#' @param resize_w the size 
#' @param resize_h the size
#' @return null
#' 
#' @export
resize_img_from_directory <- function(working_dir,img_format = "png",
                                      resize_w = 224,resize_h = 224) {
  img_match <- glue::glue("*.{img_format}")
  png_images <- list.files(working_dir,
                           img_match,
                           full.names = FALSE)
  for (a in 1:length(png_images)){
    Imgdata <- EBImage::readImage(paste0(working_dir,png_images[a]), img_format) %>% 
      EBImage::resize(w=resize_w, h=resize_h) 
    EBImage::writeImage(Imgdata, paste0(working_dir,png_images[a]), img_format,  quality = 100)
  }
  return(working_dir)
}
