# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' rotate_img_from_directory
#' 
#' rotate_img_from_directory
#' @param working_dir the dir stores the images
#' @param img_format default as png
#' @param x the rotated angle
#' @return null
#' 
#' @export
rotate_img_from_directory  <- function(working_dir,x,img_format = "png") {
  img_match <- glue::glue("*.{img_format}")
  png_images <- list.files(working_dir,
                           img_match,
                           full.names = FALSE)
  for (a in 1:length(png_images)){
    Imgdata <-  EBImage::readImage(paste0(working_dir,png_images[a]), img_format) %>% 
      EBImage::rotate(x)
    EBImage::writeImage(Imgdata, paste0(working_dir,"rotate_",x,"_",png_images[a]), img_format,  quality = 100)
  }
  return(working_dir)
}
